name: cat_trivia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.1
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.4.0
  build_runner: ^2.4.7
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true
